### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by claudesimo1990** [gilbitron/laravel-vue-pagination#141]
I can not change current  to frensh but ist not a slot :)

![image](https://user-images.githubusercontent.com/45970298/183619740-579a06fc-f25c-4a10-bbba-ba3f75b9f81f.png)

**Comment by djigir** [comment]
How I to can fix this? I need to hide (current) need show only number of page.

**Comment by Hembi** [comment]
Same problem here. This text can't be change.

**Comment by thiswallz** [comment]
I don't recommend you using this lib, has no movement for a lot of months, you will end up with a lot of problems if nobody maintains this.

**Comment by Hembi** [comment]
Which other solution do you suggest?

**Comment by thiswallz** [comment]
> 

I will fork the repo and make the changes and open this if I dont see more movement this week. we could work a bit on this.

**Comment by gilbitron** [comment]
@thiswallz Instead of going around telling people not to use this lib, why don't you submit a PR request instead?

Fwiw, the original issue that @claudesimo1990 raised is due to changes in Bootstrap v5 (which this lib doesn't officially support yet). However, I'm [working on a v4](https://github.com/gilbitron/laravel-vue-pagination/pull/147) that will add support for Bootstrap 5.

**Comment by gilbitron** [comment]
This has been fixed in v4 #147
