### ISSUE TITLE
Pagination links are not working on the server

### ISSUE THREAD

**Issue by blpraveen** [gilbitron/laravel-vue-pagination#42]
Pagination  links are not working on the server.it is working on the local host.I am using a shared hosting server. What am I doing wrong here.  It is displaying the page numbers with links not working

       <pagination :data="posts" @pagination-change-page="getResults"></pagination>

When I debug it shows the currentPage not incremented to page 2 and loading only the page 1

Is it something to do with htaccess file . I am having this issue after loading the files to the server.
If it is not related to htaccess . Why the currentPage  cannot change to page 2?

**Comment by daav7713** [comment]
im having a similar problem, its there any idea to fix it?

**Comment by gilbitron** [comment]
Can you share your full component code?

**Comment by geraldmuvengei06** [comment]
Hey I've had the same problem.
The problem was: I had passed `users` object to the pagination component where else the `getResults()` method had 'laravelData'.
Here is how I solved it.
Make sure that the object passed to the pagination component is the same as defined in the `getResults()` method like so. 

`<pagination :data="users" @pagination-change-page="getResults"></pagination>`

`getResults(page = 1) {
              axios.get('api/users?page='+page)
                .then(response => {
                  this.users = response.data;
                });
            },`
